### ISSUE TITLE
make - tarantool-php перестал собираться

### ISSUE THREAD

**Issue by YadrovSergey** [tarantool/tarantool-php#100]
После команды make вываливается такая ошибка:

/opt/php5.6/extensions/tarantool-php/src/tarantool.c: In function ‘php_tarantool_get_exception_base’:
/opt/php5.6/extensions/tarantool-php/src/tarantool.c:86:40: warning: passing argument 2 of ‘zend_hash_find’ from incompatible pointer type [-Wincompatible-pointer-types]
    if (zend_hash_find(CG(class_table), "runtimeexception",
                                        ^
In file included from /usr/include/php/20151012/Zend/zend.h:36:0,
                 from /usr/include/php/20151012/main/php.h:36,
                 from /opt/php5.6/extensions/tarantool-php/src/php_tarantool.h:4,
                 from /opt/php5.6/extensions/tarantool-php/src/tarantool.c:5:
/usr/include/php/20151012/Zend/zend_hash.h:154:30: note: expected ‘zend_string * {aka struct _zend_string *}’ but argument is of type ‘char *’
 ZEND_API zval* ZEND_FASTCALL zend_hash_find(const HashTable *ht, zend_string *key);
                              ^
/opt/php5.6/extensions/tarantool-php/src/tarantool.c:86:8: error: too many arguments to function ‘zend_hash_find’

и т.д. 

Сборка производиться ansible на Ubuntu 16/04. Пару дней назад все работало.

Здесь аналогичная ошибка https://travis-ci.org/tarantool/tarantool-php/jobs/149439259

Я с travis-ci не знаком, но из данного отчета понял что пакет перестал собираться
https://travis-ci.org/tarantool/tarantool-php/builds

**Comment by bigbes** [comment]
Еще актуально? Вы используете версию php7, а расширение взяли из ветки master.

**Comment by YadrovSergey** [comment]
Уже не актуально. Я ошибся, не ту ветку развернул. Спасибо.
