### ISSUE TITLE
Can't read query from server при вызове метода take

### ISSUE THREAD

**Issue by SonSergei** [tarantool/tarantool-php#107]
Tarantool version 1.6.8-766-g7828ac3
php-extention remi:php56-php-tarantool.x86_64

При вызове метода take из очереди валиться с ошибкой Can't read query from server
В логах tarantool:
_2016-11-07 20:16:11.041 [17630] main/159/iproto abstract.lua:267 W> Consumer 26 disconnected, release task 0_

Дамп таска
[dump.txt](https://github.com/tarantool/tarantool-php/files/576108/dump.txt)

**Comment by bigbes** [comment]
[This](https://github.com/remicollet/remirepo/pull/54) must fix the bug
