### ISSUE TITLE
Compilation fails on Fedora 25

### ISSUE THREAD

**Issue by racktear** [tarantool/tarantool-php#115]
[fedora-25] /build/usr/src/debug/php-tarantool-0.1.0.43/src/tarantool.c:86:8: error: too many arguments to function ‘zend_hash_find’
[fedora-25]     if (zend_hash_find(CG(class_table), "runtimeexception",

**Comment by racktear** [comment]
http://build.tarantool.org/job/Tarantool/job/tarantool-php/job/master/2/consoleFull#381700957c237409d-3c45-441e-a941-cfc9bde5b631

**Comment by bigbes** [comment]
You're trying to build php5 version(in master) with the php7 build files. Please, use `php7-v2` branch, for now.
```
[fedora-25] + /usr/bin/phpize
[fedora-25] Configuring for:
[fedora-25] PHP Api Version:         20151012
[fedora-25] Zend Module Api No:      20151012
[fedora-25] Zend Extension Api No:   320151012
```
