### ISSUE TITLE
[TarantoolClientError]  C++ exception (32) when call box.sql.execute

### ISSUE THREAD

**Issue by mikkiek** [tarantool/tarantool-php#120]
Hello,

I'm trying to use new SQL syntax in tarantool 1.8.1
**code:**
```
$t = new \Tarantool(
     'tarantool',
     3301,
     'test1',
     '123456'
);
$x = $t->evaluate('return box.sql.execute("CREATE TABLE test5 (ID INTEGER PRIMARY KEY, NAME VARCHAR(32))")');
var_dump($x);
```

**result:**

> [TarantoolClientError] 
> C++ exception (32)

After that any query. Almost all queries, for example
```
$x = $t->evaluate('return box.sql.execute("INSERT INTO test5 VALUES(2005, ' . rand() . ')")');
var_dump($x);
```
cause an error 
> [TarantoolClientError] 
> SQL logic error or missing database (32)

or return wrong data. At the same time, after C++ exception (32), Tarantool's console start working wit errors "SQL logic error or missing database (32)". Howver, if to do the same action in Tarantool's console, everything works like a charm. So i guess issue somewhere in PHP extension ... 

If exists any "workaround" i'll be happy to hear about them.

Thank you.

**Comment by bigbes** [comment]
Should be fixed by now in latest Tarantool
