### ISSUE TITLE
Failed to parse schema (index)

### ISSUE THREAD

**Issue by YadrovSergey** [tarantool/tarantool-php#127]
Подскажите в чем может быть проблема.
Все обращения к tarantool приводят к фатальной ошибке Failed to parse schema (index)

**Comment by YadrovSergey** [comment]
Если вызвать функции в самом tarantool:
unix/:/var/run/tarantool/social.control> socialApp.getFeedWithLastRead(1900002, 1508938001, 0)
,выполняется без ошибки.

**Comment by YadrovSergey** [comment]
Также Tarantool::ping приводит к такой ошибке: Failed to parse schema (index)

**Comment by YadrovSergey** [comment]
Подскажите в чем может быть проблема.
Все обращения к tarantool приводят к фатальной ошибке Failed to parse schema (index)

Версия php 7
tarantool модуль взят из php7-v2 tag 0.3.0
версия tarantool 1.7.5-165-ge3d97f6

Как повторить проблему
Шаг 1. Создаю пользователя:
box.schema.user.create('app', { password = 'xxx' })
Вызов php кода работает: (new \Tarantool($host, $port, 'app', 'xxx'))->ping();

Шаг 2. Даю права пользователю
box.schema.user.grant('app', 'read,write,execute', 'universe', nil)

Вызов php кода : (new \Tarantool($host, $port, 'app', 'xxx'))->ping();
Приводит к фатальной ошибке: Failed to parse schema (index)

**Comment by bigbes** [comment]
Здравствуйте, Сергей.

Скорее всего это связано с частичным изменением формата схемы в тарантуле. Я проверю попозже, благодарю за терпение.

**Comment by YadrovSergey** [comment]
Спасибо. 
Пока перешел на https://github.com/tarantool-php/client В ней такой ошибки не наблюдается.

**Comment by Totktonada** [comment]
The same as #151.
