### ISSUE TITLE
Slow reply performance when used in Php

### ISSUE THREAD

**Issue by jobs-git** [tarantool/tarantool-php#149]
Its as simple as this, in php
```php
$mysql = new Tarantool('127.0.0.101', 3301,'guest');
$val = $mysql->select('table',8);
```
I am expecting to get at least 60k req/s if I use c/c++ (async not compatible with http = 1 http req+hugely multiple database req), but In php only got 900 req/s (1http req+1database req). If I use mysql in pool mode in php (1http req+1database req), I can get around 6k req/s. So with tarantool-php its about 6x slower.

However, database usage performance on mysql vs tarantool, tarantool wins hands down (even when conditions are the same like: number of request processed+size of database)

**Comment by Totktonada** [comment]
Can you share some conditions? Average ping between a host with the connector and tarantool?

**Comment by jobs-git** [comment]
This is localhost, but I will try to check on that. I think I also tried to compare it with redis which got 32k request/s that is why I am bothered.

System
1 core
CentOS 7
PHP7
tarantool-php for php7
tarantool (any version)
(I think it also needs tarantool-c)

**Comment by Totktonada** [comment]
If you can provide a reproducer it would be ideal :)

**Comment by jobs-git** [comment]
I made a recent pull from everything, it appears to be 7x faster now! I also get the 6k req/s when compared to mysql. This aint an issue now.
