### ISSUE TITLE
tarantool-php with php 7.4

### ISSUE THREAD

**Issue by TheFatal** [tarantool/tarantool-php#150]
hey guys, can anyone build it with php 7.4 ? im gettin error with both master and 7-v2 versions

```
Makefile:191: recipe for target 'src/tarantool.lo' failed
make[1]: *** [src/tarantool.lo] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_build: make -j1 returned exit code 2
debian/rules:22: recipe for target 'binary' failed
make: *** [binary] Error 2
```

**Comment by Totktonada** [comment]
After fixing #139 the connector successfully built on php 7.4.

I look over the [list](https://github.com/php/php-src/blame/PHP-7.4.4/UPGRADING.INTERNALS) of the internal PHP API changes and it seems the only this we should consider is the following:

```
s. Typed references support
```

See the following links:

* https://wiki.php.net/rfc/typed_properties_v2#assignments_to_references
* https://gist.github.com/nikic/bb874084aaa0af6d56d6ab491a6d630b

**Comment by Totktonada** [comment]
From https://wiki.php.net/rfc/typed_properties_v2#assignments_to_references:

> Places where such replacements are necessary can be detected by searching for z/, ZEND_PARAM_ZVAL_DEREF and ZVAL_DEREF in the extension.

It seems we don't affected here: we don't write to arguments that are passed by reference, we don't use `z/` and `*ZVAL_DEREF`.

So no work remains here. Support of PHP 7.4 will be enabled in the scope of the umbrella task #137.
