### ISSUE TITLE
SQL does not support space without format

### ISSUE THREAD

**Issue by 55pingvin** [tarantool/tarantool-php#169]
SQL does not support space without format (SQL: select * from "CACHE" where key = laravelc5db41c1b37c1c9a1950d35d375c0bdf1bf5c205 limit 1)

**Comment by rybakit** [comment]
This error has nothing to do with the PHP connector, this is how SQL works in Tarantool in general, you either create spaces using SQL syntax or you create them in Lua, but make sure that the spaces have the correct format definition.

**Comment by Totktonada** [comment]
When a space has no format, there is no way to determine a name for a column. In the example you provided, SQL does not know, which column is `key`.

**Comment by 55pingvin** [comment]
Thank u! 
There was an error in the generation space
