### ISSUE TITLE
Make it possible to use field aliases in the driver

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool-php#24]
If space format is set, make it usable in the driver.

**Comment by bigbes** [comment]
What do you mean?

**Comment by Totktonada** [comment]
Closed in 31cf8a8b4c8cec99fd6e03a80b2df42d9b3cb27d?

**Comment by Totktonada** [comment]
I consider it as fixed in 31cf8a8b4c8cec99fd6e03a80b2df42d9b3cb27d.

It'll land into master in the scope of #137.
