### ISSUE TITLE
An exception is thrown while creating a tube

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool-php#26]
```php
$t = new \Tarantool();
$t->authenticate('tester', 'tester');
$t->call('queue.create_tube', ['foo', 'fifo']);
```
Output:
```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Query error 32: 
unsupported Lua type 'function'' in ...
```
The tube is created though.

**Comment by kostja** [comment]
This mis a server-side error: msgpack can't represent a Lua function object returned by crate_tube. 'call' is designed to have calling convention similar to select and return an array of tuples. To do server-side code execution, we added 'eval' to the binary protocol in 1.6, it can return arbitrary msgpack. 

We need to make eval available in PHP. Note, that eval requiers a different set of grants compared to call - it requires global 'execute' privilege, as it allows to execute arbitrary Lua code.

**Comment by kostja** [comment]
So I would consider it an enhancement request to support eval in PHP driver. 
The alternative is to make sure msgpack can pack anything on the server side.

**Comment by rybakit** [comment]
Thanks for the detailed answer. I wonder if it make sense to throw a proper exception for these sort of errors, something like `Tarantool\UnsupportedTypeException`, or at least `TarantoolExeption` (or `Exception`) to be able to handle them accordingly?

**Comment by kostja** [comment]
Yes, I agree. @bigbes ?

**Comment by bigbes** [comment]
Yes, i agree, it's part of next branch 0.1.* .

**Comment by rybakit** [comment]
Another option could be to return a special `Tarantool\LuaFunction` object, which could be later evaluated by `Tarantool::eval()`. Don't know how useful it will be though.

**Comment by bigbes** [comment]
Eval request is already created and i think #36 is all that needs to be done in this issue.

**Comment by rybakit** [comment]
@kostja @bigbes The same problem with `eval`:
```php
$t->eval('return queue.create_tube', ['foo', 'fifo']);
Exception: Query error 32: unsupported Lua type 'function'

$t->eval('queue.create_tube', ['foo', 'fifo']);
Exception: Query error 32: eval:1: '=' expected near '<eof>'
```

Also, 

```php
$t->call('queue.statistics')
Query error 22: Tuple/Key must be MsgPack array
```
but the result of the `queue.statistics` call is a table: https://github.com/tarantool/queue/blob/master/queue/abstract.lua#L356.

**Comment by kostja** [comment]
* Eugene Leonovich <notifications@github.com> [15/06/24 11:02]:
> @kostja @bigbes The same problem with `eval`:
> ```php
> $t->eval('return queue.create_tube', ['foo', 'fifo']);
> Exception: Query error 32: unsupported Lua type 'function'
> 
> $t->eval('queue.create_tube', ['foo', 'fifo']);
> Exception: Query error 32: eval:1: '=' expected near '<eof>'

You apparently are misusing eval.


Should be $t->eval("return queue.create_tube('foo', 'fifo')")

-- 
http://tarantool.org - a NoSQL database in a Lua script

**Comment by rybakit** [comment]
Ah, my bad. But could you please explain why `$t->call('queue.statistics')` fails?

**Comment by rtsisyk** [comment]
Wednesday, June 24, 2015 12:41 AM -07:00 from Eugene Leonovich <notifications@github.com>:
> 
> @kostja @bigbes The same problem with  eval :
> $t->eval('return queue.create_tube', ['foo', 'fifo']);
> Exception: Query error 32: unsupported Lua type 'function'
> 

Try $t->eval('return queue.create_tube(...)', ['foo', 'fifo']);

Eval uses loadstring() under the hood:

fun = loadstrring("eval expression")
msgpack_encode(fun(msgpack_decode(arguments)))


-- 
WBR,
   Roman Tsisyk <roman@tarantool.org>
   http://tarantool.org/ - an efficient in-memory data store and a Lua application server

**Comment by rybakit** [comment]
@rtsisyk Any hint why `call('queue.statistics')` fails with `Tuple/Key must be MsgPack array`?

**Comment by kostja** [comment]
* Eugene Leonovich <notifications@github.com> [15/06/25 11:14]:
> @rtsisyk Any hint why `call('queue.statistics')` fails with `Tuple/Key must be MsgPack array`?
> 

Could you please show here the output of queue.statistics() from
the console?


-- 
http://tarantool.org - a NoSQL database in a Lua script

**Comment by rybakit** [comment]
```
> queue.statistics()
---
- - t:
      tasks:
      - total: 1
      - ready: 1
      - taken: 0
      - buried: 0
      - done: 0
      - delayed: 0
      calls:
      - put: 1
...
```
