### ISSUE TITLE
Camelise flush_schema method

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool-php#30]
To follow [PSR-1](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md#1-overview) Coding Standards, `flush_schema` method should be renamed to `flushSchema`:

> Method names MUST be declared in camelCase.

**Comment by bigbes** [comment]
OK, i've created an alias.

С наилучшими пожеланиями, Евгений.

2015-04-11 0:38 GMT+03:00 Eugene Leonovich <notifications@github.com>:
