### ISSUE TITLE
Segmentation fault with underscore in space name

### ISSUE THREAD

**Issue by ekho** [tarantool/tarantool-php#31]
`Linux Mint 17.1 Rebecca x64`

```
PHP 5.6.7-1+deb.sury.org~trusty+1 (cli) (built: Mar 24 2015 11:21:10) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
```

Latest extension compiled from source.

Runnig `tarantool example.lua`

example.lua is:
```
box.cfg{listen=3301}
example = box.space.example
if not example then
    example = box.schema.space.create('example')
    box.space.example:create_index("primary", {type = 'hash', parts = {1, 'STR'}})
end
box.schema.user.grant('guest', 'read,write,execute', 'universe')
```

Running php built-in server `php -S localhost:8000 -t .`

open in browser http://localhost:8000/example.php

example.php is:
```
$tarantool = new Tarantool('localhost', '3301');
$tarantool->connect();
var_export($tarantool->select('example_space', 'example_key'));
```

Browser says 'Connction refused', php built-in server ends with message 'Segmentation fault'

**Comment by bigbes** [comment]
Hello, i'm sorry for long response, i'll look into it later today.

**Comment by ekho** [comment]
Same problem under php-fpm (php 5.6.7) in ubuntu 14.04

**Comment by bigbes** [comment]
I think i've fixed it, check please

**Comment by ekho** [comment]
I built extension from latest master and ...
`Apr 22 22:35:01 packer-virtualbox-iso kernel: [10643.198305] php5-fpm[17843]: segfault at 4 ip 00000000006e97aa sp 00007fff17119000 error 4 in php5-fpm[400000+7d6000]
`

**Comment by ekho** [comment]
under php-fpm I see interesting behavior:
2 requests works fine
next 2 returns 502 (segfault in kernel.log)
and next 2 works again

**Comment by ekho** [comment]
it may be somehow correlated with `pm.start_servers = 2`

**Comment by ekho** [comment]
I found a problem

It's in the underscore symbol in space name. My example is wrong.
if space called `example` all work fine. But if it called `ex_ample` segmenation fault occurs

**Comment by bigbes** [comment]
I've fixed connector. Latest master and version 0.0.12 is OK to use.
