### ISSUE TITLE
Consider renaming/aliasing eval method

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool-php#32]
[Eval](http://php.net/manual/en/reserved.keywords.php) is a reserved word in php and therefore it is not possible to override this method in userland (e.g. to allow mocking with PHPUnit). See similar issue for phpredis: https://github.com/phpredis/phpredis/issues/316

**Comment by bigbes** [comment]
Fixed in https://github.com/tarantool/tarantool-php/commit/24f28fee73de68407a1adfb9a1665600064e2add.
