### ISSUE TITLE
 ER_INVALID_MSGPACK: Invalid MsgPack - packet body

### ISSUE THREAD

**Issue by YadrovSergey** [tarantool/tarantool-php#34]
Установил tarantool, tarantool php на centos 6.6
Запускаю tarantool example.lua

```lua
box.cfg{listen=3391}
example = box.space.example
if not example then
    example = box.schema.space.create('example')
    box.space.example:create_index("primary", {type = 'hash', parts = {1, 'STR'}})
end
```
при выполнении тестового php кода:
```php
<?
$tarantool = new Tarantool('localhost', '3391');
$tarantool->connect();
var_export($tarantool->select('example', 'example_key'));
return;
?>
```
Выходит ошибка  ER_INVALID_MSGPACK: Invalid MsgPack - packet body
![2015-04-21_22-34-22](https://cloud.githubusercontent.com/assets/4640119/7260975/dcec1ad6-e876-11e4-869b-cc9d4a10f742.png)

Как ее побороть?

**Comment by bigbes** [comment]
Как вы установили tarantool и tarantool-php на centos?

**Comment by YadrovSergey** [comment]
tarantool

Как описано здесь http://tarantool.org/doc/getting_started.html#downloading-and-installing-a-binary-package для Centos
Установил на виртуальную машину битрикс http://www.1c-bitrix.ru/download/vmbitrix.php

tarantool-php По инструкции отсюда http://tarantool.org/doc/book/connectors/index.html
yum install php-cli
yum install php-dev
yum install php-pear
cd ~
git clone https://github.com/tarantool/tarantool-php.git
cd tarantool-php
phpize
./configure
make

и tarantool.so подключил в php.ini :
extension              =  /root/tarantool-php/modules/tarantool.so

**Comment by bigbes** [comment]
Попробуйте обновить tarantool до последней версии, у меня не получилось повторить вашу ошибку.

**Comment by YadrovSergey** [comment]
К сожалению ошибка повторяется. Сеть ли у вас возможность провести онлайн обучение, например через скайп, по установке tarantool и основам его работы через php. 
Или написать подробную инструкцию как установить taratool, tarantool-php на виртуальную машину http://www.1c-bitrix.ru/download/vmbitrix.php

За оплату конечно.

**Comment by bigbes** [comment]
Давайте обсудим это по электронной почте - bigbes@gmail.com
Сейчас я пытаюсь повторить поведение на виртуальной машине битрикса.

**Comment by bigbes** [comment]
Это ошибка связанная с тем, что вы пытаетесь запускать на 32х-битной машине. Сейчас я постараюсь это исправить.

**Comment by bigbes** [comment]
Окей, я пофиксил это в последнем мастере. По другим вопросам - обращайтесь на почту.
