### ISSUE TITLE
Add support for auto_increment function for space

### ISSUE THREAD

**Issue by efisuby** [tarantool/tarantool-php#38]
There is an auto_increment function for inserting via lua console. But there is no for php code.
This function also descibed in docs http://tarantool.org/doc/user_guide.html#box.space

**Comment by bigbes** [comment]
This command is not supported by IProto -> you must call 'box.space.<space-name>:auto_increment' stored procedure.

**Comment by efisuby** [comment]
that was a point for me. Do not use call method in my case. I think that it is the only choice for now
