### ISSUE TITLE
Internal error on select by a space id and an index name

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool-php#42]
``` php
const SPACE_INDEX = 288;
(new Tarantool())->select(SPACE_INDEX, [], 'name');
```

fails with:

```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Internal Error' ...
```

**Comment by bigbes** [comment]
Ok, i've found where is error, but until i fix it, i suggest you to authenticate before start sending commands or using '_index'/'_vindex' instead of number.

**Comment by bigbes** [comment]
Sorry for long response. Everything must be OK by now. If it's not - please, reopen this bug and attach more information. Thank you!

**Comment by rybakit** [comment]
@bigbes Looks like it's still not possible to use index id. Now I get

```
Uncaught exception 'Exception' with message 'Failed parsing schema (index) or memory issues' ...
```

**Comment by rybakit** [comment]
Also, in this test case https://github.com/tarantool/tarantool-php/blob/master/test/MockTest.php there is a defined `SPACE_INDEX` constant which is not used anywhere in the tests.

**Comment by bigbes** [comment]
This 'bug' requires major rewriting of schema.
If you're using `SPACE_ID` as number, please, use `INDEX_ID` as number too, for now.

**Comment by Totktonada** [comment]
NB: The problem appears only when a schema is not fetched at the moment of select() (or when it is obsoleted and does not contain relevant space).
