### ISSUE TITLE
authenticate() returns true on invalid credentials

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool-php#44]
```php
$result = (new Tarantool())->authenticate('guest', 'incorrect_password');
var_dump($result); // bool(true)
```

**Comment by rybakit** [comment]
It still returns `true` for me.

**Comment by bigbes** [comment]
It must throw exception - try to update version to latest from master.

С наилучшими пожеланиями, Евгений.

2015-06-02 20:24 GMT+03:00 Eugene Leonovich <notifications@github.com>:

**Comment by rybakit** [comment]
https://github.com/rybakit/travis-sandbox/blob/b21968ae3ff2e79a4a70504927adb5ac0cc25612/test.php
https://travis-ci.org/rybakit/travis-sandbox/builds/65140234

**Comment by rybakit** [comment]
@bigbes Should this Issue be reopened?

**Comment by bigbes** [comment]
@rybakit Please, give me test case, i can't reproduce it :( It must throw exception, but it don't, if i get it right.

**Comment by rybakit** [comment]
@bigbes Did you follow the links I posted? it's reproducible on Travis (I checked it today). Here are the files: https://github.com/rybakit/travis-sandbox/tree/b21968ae3ff2e79a4a70504927adb5ac0cc25612

**Comment by rybakit** [comment]
@bigbes I think it's because of the "guest" user. For other users it indeed throws `Query error 47: Incorrect password supplied for user 'user_foo'' ...`.

**Comment by rybakit** [comment]
And here is the test case: https://github.com/tarantool-php/client/blob/master/tests/Integration/ConnectionTest.php#L110

**Comment by bigbes** [comment]
Then it's ok, guest user is OK to connect with any password. But request
must be encoded like:
```{0x23:"guest", 0x21:[]}```
and that's how it's encoded in 'tarantool-php PECL' driver (password is
simply skipped)

С наилучшими пожеланиями, Евгений.

2015-06-17 18:39 GMT+03:00 Eugene Leonovich <notifications@github.com>:

**Comment by rybakit** [comment]
Is it documented somewhere that for the guest user the password should be omitted?

**Comment by kostja** [comment]
* bigbes <notifications@github.com> [15/06/17 20:22]:
> Then it's ok, guest user is OK to connect with any password. But request
> must be encoded like:
> ```{0x23:"guest", 0x21:[]}```
> and that's how it's encoded in 'tarantool-php PECL' driver (password is
> simply skipped)

Actually I believe I fixed the server so that when you supply a
password for the guest user, it throws an error.

So, Eugene, you can fix the driver to pass any credential to the
server intact, including credentials for the guest user: if there 
is a password supplied for guest, the server will return an error.


-- 
http://tarantool.org - a NoSQL database in a Lua script

**Comment by kostja** [comment]
* Eugene Leonovich <notifications@github.com> [15/06/17 20:22]:
> Is it documented somewhere that for the guest user the password should be omitted?
> 

It used to be ignored. Then someone else stumbled upon this,
thinking that it can be set. So we no longer ignore it: it cannot
be set at server side and if is supplied by the client it's an
error. 

Apparently the driver was written before we fixed the server, and
silently "skips" the passwod for the guest user.. If this is the
case, the driver needs to be fixed as I described in the previous
comment.

-- 
http://tarantool.org - a NoSQL database in a Lua script

**Comment by rybakit** [comment]
@kostja Thanks for the explanation.
@bigbes A small note: IMHO, there is not much value in returning a boolean result from this function since there is an exception thrown on error. What do you think?

**Comment by kostja** [comment]
@bigbes?

**Comment by bigbes** [comment]
@kostja 
@bigbes

**Comment by bigbes** [comment]
Sorry for long response. I've replaced retval of authenticate with NULL. Everything must be OK by now. If it's not - please, reopen this bug and attach more information. Thank you!

**Comment by rybakit** [comment]
> So, Eugene, you can fix the driver to pass any credential to the server intact, including credentials for the guest user: if there is a password supplied for guest, the server will return an error.

@bigbes It still doesn't throw an error if I supply a password for the guest user:

```
(new Tarantool('tarantool'))->authenticate('guest', '');
(new Tarantool('tarantool'))->authenticate('guest', 'incorrect_password');
```
I expect this code to throw `Incorrect password supplied for user 'guest'` exception.

**Comment by rybakit** [comment]
@bigbes What about an empty sting as a password?

```php
(new Tarantool())->authenticate('guest', '');
```
Still no exception is thrown. However, the python driver raises an error:

```python
import tarantool

con = tarantool.Connection('tarantool', 3301)
con.authenticate('guest', '')
```
```sh
tarantool.error.DatabaseError: (47, "Incorrect password supplied for user 'guest'")
```

**Comment by bigbes** [comment]
This doesn't make any sense, but I've fixed this.

With best regards, Eugene.

2016-03-10 1:07 GMT+03:00 Eugene Leonovich <notifications@github.com>:

**Comment by rybakit** [comment]
@bigbes Sorry for being annoying, but I found that `authenticate()` doesn't allow `null` as a password for the "guest" user. I suppose that `$t->authenticate('guest');` should be equal to `$t->authenticate('guest', null);`?
