### ISSUE TITLE
Script hangs on double connect() call

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool-php#45]
```php
$t = new Tarantool();

var_dump($t->connect());
var_dump($t->connect());
```
results in:
```
bool(true)
(hang for a few minutes)
bool(false)

**Comment by bigbes** [comment]
Test `test_01_create_test_ping_and_close` also hangs?

**Comment by bigbes** [comment]
Can't reproduce.

**Comment by rybakit** [comment]
It's still hangs for me (I run it on centos 6 VM).

Btw, I work on a [pure php implementation of the Tarantool client](https://github.com/tarantool-php/client). I created an adapter for the pecl driver to test compatibility of both clients (that's how I found bugs in the pecl driver). So if you interest you can test your pecl driver against my test suite:

```
$ TARANTOOL_CLIENT=pecl phpunit -v --testsuite Integration --exclude-group pureonly
```

**Comment by rybakit** [comment]
My `/etc/php.d/tarantool.ini` file:

```
extension = tarantool.so
```

**Comment by rybakit** [comment]
Looks like it also hangs on Travis (602 seconds to finish tests): https://travis-ci.org/tarantool-php/client/jobs/65038648

**Comment by bigbes** [comment]
It's only repeatable on your testing system..

**Comment by rybakit** [comment]
Indeed, after upgrading Tarantool to 1.6.5-161-g07e20b9 the problem was gone (I think it was 1.6.4 before).

**Comment by rybakit** [comment]
I found why it hangs on Travis.

Works:
```php
(new Tarantool())->connect();
(new Tarantool())->connect();
```

Hangs:
```php
$t1 = new Tarantool();
$t1->connect();
$t2 = new Tarantool();
$t2->connect();
```

**Comment by bigbes** [comment]
I've fixed it in the latest master.
