### ISSUE TITLE
Add upcoming PHP7 support

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool-php#46]

**Comment by rzst** [comment]
Here's an up-to-date branch with PHP7 support: https://github.com/tony2001/tarantool-php/tree/php7_tnt16

**Comment by tony2001** [comment]
Here's my branch with PHP7 support: https://github.com/tony2001/tarantool-php/tree/php7_tnt16

**Comment by bigbes** [comment]
@tony2001 Thank you, Tony! Is there anything we can do to merge your branch? To support both versions (PHP5 and PHP7).

**Comment by bigbes** [comment]
Work in progress on branch php7-v1

**Comment by bigbes** [comment]
First working version on branch [`php7-v1`](https://github.com/tarantool/tarantool-php/tree/php7-v1).
In the future, php7 driver would be rewritten with:
1) pconnect branch
2) tarantool-c driver

**Comment by bigbes** [comment]
First working version on branch [`php7-v2`](https://github.com/tarantool/tarantool-php/tree/php7-v2).

**Comment by jobs-git** [comment]
Hi, what is the status for php7 support

**Comment by Totktonada** [comment]
It is mostly done in the `php7-v2` branch. I'll update it with fixes for PHP 7.3 (#139) and PHP 7.4 (#150), will enable packages building and deployment (#117) and after this will switch the branch `php-7-v2` to `master` (#137).

This activity is tracked in #137 anyway, so I'll close this issue.

**Comment by jobs-git** [comment]
Hi, please dont remove branch for php 7.2, cause php 7.3 has some breaking changes. tnx!

**Comment by Totktonada** [comment]
I'll add build-time conditions (similar to ones in PR #148), so the connector will build for php-7.{0-4}.
