### ISSUE TITLE
php5-tarantool package doesn't work with thread safe version of php

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool-php#47]
Doing `apt-get install php5-tarantool` and then enabling this module in php fails on Travis, as Travis has [thread-safe version of php](https://github.com/travis-ci/travis-ci/issues/2800) and it seems that `php5-tarantool` does not support ZTS.

**Comment by ekho** [comment]
tarantool-php should be built with zts version of php-dev to be comatible with zts

**Comment by bigbes** [comment]
We built only standard version of tarantool-php (with distro version of php). To build custom version of tarantool-php with support for custom php version (e.g. built with ZTS) you need to build it on your own.

**Comment by rybakit** [comment]
@bigbes Fair enough. Feel free to close the issue.
