### ISSUE TITLE
Unable to build tarantool extension as static

### ISSUE THREAD

**Issue by tony2001** [tarantool/tarantool-php#55]
Put the sources into ext/tarantool, run ./buildconf, then ./configure --enable-tarantool (that's the correct option for extensions not linking against any libs), see lots of errors.

**Comment by bigbes** [comment]
Thanks for bug report. I'll look into it.

**Comment by bigbes** [comment]
It happens due to path of php_tarantool.h file - it's located in src subdir, so buildsystem can't find it.

**Comment by tony2001** [comment]
Right. Also because all the other files are in a subdir.
Try building PHP out of source dir, you'll see what I mean:
mkdir BUILD_TEST; ../configure --with-tarantool && make

**Comment by bigbes** [comment]
@tony2001 is there any way to create this subdirectory? Or the only way is to move sources to root of the tree?
In-source-build i've been able to fix, but OOS is not so simple to fix.

**Comment by tony2001** [comment]
I don't know of any solution that wouldn't be a dirty hack.
