### ISSUE TITLE
PHP. "Failed to parse query" on 1.6.7

### ISSUE THREAD

**Issue by OffRoadshik** [tarantool/tarantool-php#61]
On reproducing an example on PHP from the documentation, Tarantool returns an error "Failed to parse query" on any operation (insert, select...).

**Comment by rybakit** [comment]
Could you please paste the code you are trying to run?

**Comment by OffRoadshik** [comment]
Сertainly.
<?php

$tarantool = new Tarantool("127.0.0.1", 3305);

try {
    $q = $tarantool->insert("examples", [99999, "BB"]);
    print "Insert succeeded\n";
    
}
catch (Exception $e) {
    echo "Exception: ", $e->getMessage(), "\n";
}

$tarantool->close();

**Comment by bigbes** [comment]
Now everything must be ok.

**Comment by bigbes** [comment]
No, I'm sorry. It seems like it wasn't all.

**Comment by bigbes** [comment]
Ok, now it's fixed :)

**Comment by bigbes** [comment]
@OffRoadshik everything works fine?

**Comment by OffRoadshik** [comment]
Yes, It's ok. Thanks.
