### ISSUE TITLE
Configure on Mac OS

### ISSUE THREAD

**Issue by kamenevn** [tarantool/tarantool-php#65]
Can I build tarantool-php on Mac OS?

My config.log http://pastebin.com/raw/3K5wfH0i

**Comment by bigbes** [comment]
Hello, @kamenevn. I'll look into it later

**Comment by rybakit** [comment]
@kamenevn If you have problems installing *tarantool-php* on Mac OS, try this [pure php client](https://github.com/tarantool-php/client).

**Comment by bigbes** [comment]
@kamenevn I've successfully build tarantool-php on my Mac OS X, 

```
blikh@bigbes-laptop:~/src/tarantool-php$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
blikh@bigbes-laptop:~/src/tarantool-php$ php --version
PHP 5.5.30 (cli) (built: Oct 23 2015 17:21:45)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```

**Comment by kamenevn** [comment]
@bigbes
I use MacOS Yosemite (10.10.4).

>>phpize
Configuring for:
PHP Api Version:         20121113
Zend Module Api No:      20121212
Zend Extension Api No:   220121212

>> autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

>> php -v
PHP 5.5.31 (cli) (built: Jan  8 2016 08:33:30)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans

How to find error?
I run ./configure by user and by root, but error is the same(config.status: error: could not create config.h)

**Comment by bigbes** [comment]
@kamenevn I read log multiple times, and the only thing that leads to it is:
```
clang: error: no such file or directory: '/usr//opt/local/lib'
```
and that leads us to
```
$ ./configure --with-libdir=/opt/local/lib
```

**Comment by bigbes** [comment]
@kamenevn Also, you use php55 from php tap? I've tested on PHP that's shipped with Mac OS X

**Comment by rybakit** [comment]
I was able to build the extension on Yosemite (10.10.5) successfully. The environment is pretty much the same to @kamenevn's:

```
$ phpize
Configuring for:
PHP Api Version:         20121113
Zend Module Api No:      20121212
Zend Extension Api No:   220121212
```
```
$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```
```
$ php -v
PHP 5.5.30 (cli) (built: Oct  3 2015 23:46:56)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```

**Comment by kamenevn** [comment]
Thank you for your time. Apparently the problem is specific to my computer

**Comment by bigbes** [comment]
@kamenevn any updates? I've fixed driver, now tests are OK

**Comment by bigbes** [comment]
@kamenevn feel free to reopen this issue.
