### ISSUE TITLE
update vs evaluate - большое потребление пямяти

### ISSUE THREAD

**Issue by YadrovSergey** [tarantool/tarantool-php#67]
Почему происходит такая разница в использовании памяти.

Вариант 1. Использую функцию update . Затрачено около 90МБ
![update](https://cloud.githubusercontent.com/assets/4640119/12811615/b7cfd368-cb3e-11e5-9b1b-cd12a8847af8.png)

Вариант 2. В php формирую update код на lua и исполняю его функцией evaluate.  Затрачено около 3МБ
![evaluate](https://cloud.githubusercontent.com/assets/4640119/12811679/0db1c7e6-cb3f-11e5-8fe2-eceee53cacdf.png)

В чем может быть проблема?

**Comment by bigbes** [comment]
В том, что во время перевода операций из представления клиента в представление сервера (для update) создаётся еще одна копия данных, а evaluate/call просто пакует предоставленные ему данные.

**Comment by bigbes** [comment]
В следующей версии я планировал обойтись без промежуточного представления, что позволит сократить потребление памяти и ускорить работу Update
