### ISSUE TITLE
random connect timeout 

### ISSUE THREAD

**Issue by kostja** [tarantool/tarantool-php#68]
Костя, а вот это что за проблема?  
 - какое конкретно нестабильное поведение было замечено и какие риски рстаются?

Было много проблем, озвученных Рушбой, в том числе очень мешающая проблема с persistent connect, проявляющаяся под нагрузкой. При включении pconnect и выполнении Tarantool->connect мы висим 10 секунд. При этом игнорируется указанный таймаут для тарантула (сейчас 5 секунд). Это можно воспроизвести даже без нашего кода, сделав что-то наподобие <?php dl('tarantool16.so'); ini_set('tarantool.persistent', 1); $Tarantool->connect(); ?> и вызывать в несколько потоков через curl. Чем больше будет потоков, тем выше процент "залипания".

**Comment by bigbes** [comment]
Fixed on branch [timeouts](https://github.com/tarantool/tarantool-php/tree/timeouts)
