### ISSUE TITLE
Rename the debian package to php5-tarantool

### ISSUE THREAD

**Issue by sathieu** [tarantool/tarantool-php#7]
I've seen your package in the debian NEW queue [1].

The binary package doesn't follow the naming convention: it should be named php5-tarantoll. Also, we usually name the source package php-tarantool.

Some more remarks:
- please consider making a PECL package, then using pkg-php-tools: http://anonscm.debian.org/gitweb/?p=pkg-php/pkg-php-tools.git;a=blob;f=debian/README.PEAR
- check your package with lintian, it has some possible improvements (like the dep5 url which is obsolete)

[1]: https://ftp-master.debian.org/new/tarantool-php_1.0-1.html

**Comment by bigbes** [comment]
Fixed

**Comment by sathieu** [comment]
thanks
