### ISSUE TITLE
Can't query space by name

### ISSUE THREAD

**Issue by evgeny-sureev** [tarantool/tarantool-php#72]
Hello.

If I try to run query on space using space ID, everything is ok, but if I use space name, exception is thrown.

What it can be?

Space with that name exists in the tarantool, and I am able to select from it using tarantool console command `box.space.spacename:select{}`

```
<?php
$client = new Tarantool();

var_dump($client->select(513)); // OK, dumps some tuples

var_dump($client->select("spacename")); // Fatal error:  Uncaught exception 'Exception' with message 'Failed to parse query'
```

**Comment by bigbes** [comment]
What's your version of Tarantool?

**Comment by evgeny-sureev** [comment]
Tarantool 1.6.7-630-geab01da

**Comment by bigbes** [comment]
@evgeny-sureev how did you install this extension? via git?

**Comment by bigbes** [comment]
@evgeny-sureev actual version of driver is 0.1.0, btw

**Comment by bigbes** [comment]
Must be fixed in latest master.

**Comment by bigbes** [comment]
Feel free to reopen this issue, if it's still affects you
