### ISSUE TITLE
Unable to read large response

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool-php#74]
```php
$t = new Tarantool();

$data = str_repeat('x', 1024 * 1024);
$result = $t->eval('return ...', [$data]);

var_dump($data === $result[0]);
```
outputs

```sh
Fatal error: Uncaught exception 'Exception' with message 'Can't read query from server'
```

**Comment by YadrovSergey** [comment]
У меня такая же проблема. При получении сообщений блога из tarantool, если у них много текста, то выводится Exception: Can't read query from server
Т.е. для обычного блога tarantool-php не подходит.
Данная ошибка воспроизводится на версии php 5.4.  На 5.5 пока не наблюдаю.

**Comment by bigbes** [comment]
Fixed in latest master
