### ISSUE TITLE
An exception occurs while trying to disable connection retries

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool-php#83]
``` php
$t = new Tarantool();

ini_set('tarantool.retry_count', 0);

$t->ping();
```

outputs

```
Uncaught exception 'Exception' with message '(null)'
```

**Comment by Totktonada** [comment]
Now `retry_count` option means the following:

- `retry_count = 1` — perform only one connection attempt, fail if it is unsuccessful;
- `retry_count = N` (N >= 2) — perform N attempts to connect and ignore transient errors (connection failures) for the first (N-1) attempts.

So `retry_count = 1` is what you want to achieve with `retry_count = 0`.

`retry_count = 0` has no sense and an error should make it clear.

I'm not sure whether we should change meaning of the option (I'm afraid of behaviour changes between versions). I'll update the [discussion](https://github.com/tarantool/tarantool-php/pull/145#discussion_r241255667).

**Comment by rybakit** [comment]
> retry_count = 0 has no sense and an error should make it clear.

I would agree with your points if the setting was called `number_of_attemps`, but the *re* prefix already implies that something will be *repeated*. So it makes perfect sense to me to have `retry_count = 0` and in the other thread I gave you examples of well-established APIs that follow this logic. Maybe you have a counterexample? To be honest, I've never seen anything like that before.

**Comment by Totktonada** [comment]
I have updated the linked discussion.
