### ISSUE TITLE
A greeting response is not validated

### ISSUE THREAD

**Issue by rybakit** [tarantool/tarantool-php#84]
``` php
$t = new Tarantool('0.0.0.0', 8000);

ini_set('tarantool.request_timeout', 2);

$t->ping();
```

throws `Can't read query from server (failed to read length)` even if the server didn't send a greeting response yet.

**Comment by rybakit** [comment]
Looks like the connector is silently ignoring an empty/wrong greeting instead of raising an error. Literally, I can connect to any non-Tarantool server and it will not complain about it:

```
$t = new Tarantool('127.0.0.1', 3306); //  mysql server
$t->connect(); // true

$t = new Tarantool('127.0.0.1', 6379); //  redis server
$t->connect(); // true
```

Would be nice to validate a greeting message (both lines, the server name + version *AND* the base64 encoded salt) during the connection and throw an exception if it's not a Tarantool server.

Also, check this: https://github.com/tarantool/nginx_upstream_module/blob/master/src/ngx_http_tnt_handlers.c#L117
And this: https://github.com/tarantool-php/client/blob/stream_conn/tests/GreetingDataProvider.php

**Comment by bigbes** [comment]
Fixed on branch `php7-v2`
