### ISSUE TITLE
Passing boolean to 'call' causes "Invalid MsgPack - packet length"

### ISSUE THREAD

**Issue by zaglex** [tarantool/tarantool-php#87]
Hi!
I have a problem with tarantool 1.6 and php-connector from php7-v1 branch.

How to reproduce:
just pass boolean value to 'call':
```
$tnt = new Tarantool('localhost', 3301);
$tnt->call([true]);
```
You should see this in tarantool log:
```
iproto iproto.cc:450 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet length
```
P.S.
Tarantool version: 1.6.8-653-g2e4a17d

**Comment by zaglex** [comment]
I suppose that problem is caused not by insert itself, but by mechanism responsible for errors throwing.
I've got the same result with just calling of not existing lua-function:
for($i = 0; $i < 250; $i++){
     $tnt->call('iDoNotExist',['data']);
}

**Comment by rybakit** [comment]
@zaglex What is your concern actually and what result do you expect to see?

**Comment by zaglex** [comment]
1. With insert I expect to see an error message _"Query error 3: Duplicate key exists in unique index 'primary' in space 'myitems'"_ in tarantool response.
2. With call to not existing function I expect to see an error message _"Query error 33: Procedure 'iDoNotExist' is not defined"_.

But in both cases I see error message "Can't read query from server" in tarantool response and
next record in tarantool log:
_"iproto sio.cc:251 !> SystemError accept, called on fd 13, aka 0.0.0.0:3311: Too many open files"_

**Comment by zaglex** [comment]
Of course, call to not existing function is not quite a problem - it is just an example.
But call to insert is a real problem, because we may have many "duplicate key" inserts during one script run.

**Comment by zaglex** [comment]
Oh, sorry, I've opened two issues, and my comment relates to another issue, I'll move it there.
