### ISSUE TITLE
Tarantool exceptions enhancement: custom classes, lua traceback

### ISSUE THREAD

**Issue by zaglex** [tarantool/tarantool-php#88]
It would be great to improve exceptions thrown by Tarantool:

1. Use separate class, e.g. TarantoolException, or even hierarchy of classes.
2. For "query errors" you could pass error code as $code parameter, so that it would be available through $exception->getCode().
3. Save lua-traceback to some custom field of your exception object. Currently we should use xpcall with debug.traceback(), and return traceback manually.

**Comment by bigbes** [comment]
1 and 2  - It's planned (and partially implemented) on PHP7 branch. Please, look at https://github.com/tarantool/tarantool-php/issues/36
3 - It must be implemented on Tarantool's side. Please, look at https://github.com/tarantool/tarantool/issues/677

**Comment by bigbes** [comment]
1 and 2 - done on branch `php7-v2`.
3 - Please, file separate issue, or follow original ticket on Tarantool.
