### ISSUE TITLE
Limitations on 'call' response size in php7-v1

### ISSUE THREAD

**Issue by zaglex** [tarantool/tarantool-php#90]
When I try to return 300 tuples from lua-function, I get "Can't read query from server" and nothing in tarantool log.

P.S.
1. 200 tuples and less are ok in my case.
2. Tuples are small enough: 5 nums + table of 0-6 nums

**Comment by bigbes** [comment]
Hi! Can you provide a testcase? I can't reproduce it.

**Comment by zaglex** [comment]
This example is little bit artificial, but it is easy to reproduce and it shows the problem:
```lua
function myfetch(count)
    local i = 0
    result = {}
    while i < count do
        table.insert(result, {1,2,3,4,5,6,7,8,9,10})
        i = i + 1
    end

    return result
end
```

```php
$count = 1487;
$response = $tarantool->call('myfetch', [$count]);
```
In my case it works when $count <=1486, but it crashes when $count > 1486.
