### ISSUE TITLE
Exception code

### ISSUE THREAD

**Issue by R-omk** [tarantool/tarantool-php#92]
I've tried branch php7-v1 and found problem with exception code.

My lua func1's code
```lua
local CONST_TIMEOUT_PULL=902
box.error{code = CONST_TIMEOUT_PULL, reason = 'timeout pull'}
```
php code
```php
try {
	$res = $tarantool->call("func1", "");		
} catch (Throwable $e) {
	print_r($e->getCode()."\n");
	print_r($e->getMessage());
}
```

I've expected to see something like

```
902
timeout pull
```

But I've seen 

```
0
Query error 902: timeout pull
```

**Comment by bigbes** [comment]
Will be fixed with https://github.com/tarantool/tarantool-php/issues/36.
Closed as duplicate
