### ISSUE TITLE
Unexpected behaviour when reference to array element is created

### ISSUE THREAD

**Issue by zaglex** [tarantool/tarantool-php#93]
Example:

```lua
function myfunc(data)
end
```

```php
$data = [
     'key1' => 'value1',
];
$link = &$data['key1'];
$tarantool->call('myfunc', [$data]);
```

Problem:
Inside lua-function 'myfunc' i see that data['key1'] is null (cdata<void *>: NULL).

Expected behaviour:
data['key1'] must be 'value1' in lua-function.

**Comment by bigbes** [comment]
This bug was due to new type in PHP7 - "IS_REFERENCE". It must be fixed now on branch "php7-v2"
