### ISSUE TITLE
Seg fault if delete tuple through loop

### ISSUE THREAD

**Issue by baltazor5000** [tarantool/tarantool-php#98]
Hello.
I have Tarantool 1.7.1-123-g17673d5 and php 7.0.9
If I try delete tuple through loop, I have segmentation fault.
PHP script example:
`<?php
$tnt = new Tarantool('remote_ip:3301');
$tnt->connect();
$space = "test";
$key = "test2";
for($i=0;$i<=1000;$i++) {
$tnt->delete($space, $key . $i);
}`

If I try delete tuple through loop with $i=1000 and $i<=100000 - All ok.

**Comment by bigbes** [comment]
Please, try to use branch `php7-v2`. And sorry for long response.
